export const animateMerge = (g1, g2, specs) => {
    g1.transition().delay(specs.animationDuration / 2).duration(specs.animationDuration)
        .attr("transform", "translate(200, 0)")
    g1.selectAll('g')
        .attr("opacity", 1)
        .transition().duration(specs.animationDuration)
        .attr("opacity", 0)
    g1.selectAll('.dot')
        .attr('opacity', 1)
        .style('fill', 'black')
        .transition().ease(d3.easePoly).duration(specs.animationDuration)
        .attr("opacity", .3)
        .style('fill', specs.color1)

    g2.transition().delay(specs.animationDuration / 2).duration(specs.animationDuration)
        .attr("transform", "translate(200, 0)")
    g2.selectAll('g')
        .attr("opacity", 1)
        .transition().duration(specs.animationDuration)
        .attr("opacity", 0)
    g2.selectAll('.dot')
        .attr('opacity', 1)
        .style('fill', 'black')
        .transition().ease(d3.easePoly).duration(specs.animationDuration)
        .attr("opacity", .3)
        .style('fill', specs.color2)
}